version: "3"

tasks:
  postpull:
    desc: Run after pulling new code
    cmds:
      - yarn install
      - yarn workspaces foreach -pv run ws:clean
      - yarn workspaces foreach -ptvA run ws:build
  ci:build:
    desc: "Build assuming CI environment"
    cmds:
      - yarn install
      - yarn workspaces foreach -ptv --no-private run ws:build
  ci:test:
    desc: "Test built artifacts"
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:test
  ci:publish:
    desc: "Publish built artifacts"
    cmds:
      - yarn workspaces foreach -v --no-private npm publish --tolerate-republish --access public
