# https://taskfile.dev/#/installation
version: "3"

tasks:
  postpull:
    desc: Run after pulling new code
    cmds:
      - yarn install
      - yarn workspaces foreach -pv --no-private run ws:clean
      - yarn workspaces foreach -ptv --no-private run ws:build
  ci:setup:
    desc: "Install dependencies"
    cmds:
      - yarn install
  ci:build:
    desc: "Build assuming CI environment"
    cmds:
      - yarn workspaces foreach -ptv --no-private run ws:build
  ci:test:
    desc: "Test built artifacts"
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:test
  ci:publish:
    desc: "Publish built artifacts"
    cmds:
      - yarn workspaces foreach -v --no-private npm publish --tolerate-republish --access public
  ci:version:
    desc: "Bump ('decline', 'major', 'minor', 'patch', 'prerelease') or Set the version of all packages"
    cmds:
      - yarn workspaces foreach -v --no-private version {{.CLI_ARGS}}
