version: 3

tasks:
  announce:
    vars:
      SKIP_ANNOUNCE: '{{default "true" .SKIP_ANNOUNCE}}'
      MESSAGE: '{{default "Hello, world" .MESSAGE}}'
      SLACK_WEBHOOK_URL: '{{.SLACK_WEBHOOK_URL}}'
    cmds:
      - |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"{{.MESSAGE}}"}' $SLACK_WEBHOOK_URL
    status:
      - '[ "{{.SKIP_ANNOUNCE}}" = "true" ]'
