openapi: 3.0.1
info:
  version: 0.0.0
  title: Example
x-optic-naming-checks:
  responseProperties: camelCase
  applyNamingRules: whenAdded
paths:
  "/city/{code}":
    parameters:
      - name: code
        in: path
        schema:
          type: string
        required: true
    get:
      operationId: getExamples
      responses:
        200:
          description: "ANBC"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  code:
                    type: string
                  population_size:
                    type: integer
                  country_code:
                    type: string
                required:
                  - name
                  - code
