version: "3"

env:
  DOCKER_REGISTRY: 513974440343.dkr.ecr.us-east-1.amazonaws.com
  REPO: '{{default .Env.REPO "demo" }}'

tasks:
  demo:build:
    desc: Build demo site
    cmds:
      - task: :workspaces:build
      # setting $CI directly on the build command is required due to the way env
      # inheritance winds up working here. setting this in the env block on this
      # task will not work.
      - CI=false yarn build-demo

  demo:docker:build:
    desc: Build and package demo site as a Docker container
    vars:
      TAG:
        sh: echo $(../../bin/clean-docker-tag $TAG)
    cmds:
      - task: demo:build
      - docker build . -f Dockerfile_demo -t $DOCKER_REGISTRY/$REPO:{{.TAG}}

  demo:docker:push:
    vars:
      TAG:
        sh: echo $(../../bin/clean-docker-tag $TAG)
    cmds:
      - docker push $DOCKER_REGISTRY/$REPO:{{.TAG}}
      - |
        if [[ "{{.TAG}}" =~ ^release-b ]]
        then
          docker tag $DOCKER_REGISTRY/$REPO:{{.TAG}} $DOCKER_REGISTRY/$REPO:latest
          docker push $DOCKER_REGISTRY/$REPO:latest
        fi
      - task: :docker:slack-notifier
        vars:
          TAG: "{{.TAG}}"

  demo:ci:
    desc: CI workflow
    deps: [":workspaces:setup"]
    cmds:
      - task: :workspaces:clean
      - task: demo:docker:build
      - task: demo:docker:push
