version: "3"

tasks:
  clean:
    desc: Removes UI's build directories
    cmds:
      - rm -rf build

  ci:
    - task: cloud-spec-viewer:ci

  #
  # docker namespace
  #
  docker:build:
    desc: Package site as a Docker container
    vars:
      TAG:
        sh: echo $(../../bin/clean-docker-tag {{.TAG}})
    cmds:
      - |
        docker build . \
          -t $DOCKER_REGISTRY/{{.REPO}}:{{.TAG}} \
          --build-arg APP={{.REPO}}

  docker:push:
    vars:
      TAG:
        sh: echo $(../../bin/clean-docker-tag $TAG)
    cmds:
      - docker push $DOCKER_REGISTRY/{{.REPO}}:{{.TAG}}
      - |
        if [[ "{{.TAG}}" =~ ^release-b ]]
        then
          echo "tagging and pushing 'latest'"
          docker tag $DOCKER_REGISTRY/{{.REPO}}:{{.TAG}} $DOCKER_REGISTRY/{{.REPO}}:latest
          docker push $DOCKER_REGISTRY/{{.REPO}}:latest
        fi

  #
  # cloud-spec-viewer namespace
  #
  cloud-spec-viewer:build:
    desc: Build cloud-spec-viewer site
    cmds:
      - task: :workspaces:build
      - >
        BUILD_PATH=build-cloud-spec-viewer
        yarn build:cloud
    sources:
      - src/**
      - package.json
      - '**.ts'
      - scripts/*spec*
    generates:
      - build-cloud-spec-viewer/**

  cloud-spec-viewer:docker:build:
    - task: cloud-spec-viewer:build
    - task: docker:build
      vars:
        REPO: cloud-spec-viewer

  cloud-spec-viewer:docker:push:
    vars:
      TAG:
        sh: echo $(../../bin/clean-docker-tag $TAG)
    cmds:
      - task: docker:push
        vars:
          REPO: cloud-spec-viewer
      - task: :docker:slack-notifier
        vars:
          TAG: "{{.TAG}}"
          REPO: cloud-spec-viewer

  cloud-spec-viewer:ci:
    desc: CI workflow
    deps: [":workspaces:setup"]
    cmds:
      - task: cloud-spec-viewer:docker:build
      - task: cloud-spec-viewer:docker:push
        vars:
          REPO: cloud-spec-viewer
