version: '3'

tasks:
  deploy:
    desc: Deploy the website to S3
    cmds:
      - bin/deploy
    env:
      APP_ENV: '{{default "staging" .APP_ENV}}'
      DRY_RUN: '{{default "true" .DRY_RUN}}'
      SKIP_VERIFY: '{{default "false" .SKIP_VERIFY}}'

  install-deps:
    - yarn install

  build:
    desc: Build the website
    deps: [install-deps]
    cmds: [yarn build]

  start:
    desc: Run the website locally
    deps: [install-deps]
    cmds: [yarn start]
