name: Build UI projects

on:
  push:
    branches:
      - release
      - develop
    paths-ignore:
      - website/**
      - .github/**
      - "**.md"
  pull_request:
    branches: [develop]
    paths-ignore:
      - website/**
      - .github/**
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # v2.3.3
        with:
          token: ${{ github.token }}
      - run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]
          then
            echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          else
            echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
      - run: |
          if [ "$BRANCH" = "release" ]; then
            echo "BUCKET=optic-demo-website-production" >> $GITHUB_ENV
            echo "CLOUDFRONT_DIST=E1OKG70IUZ446Q" >> $GITHUB_ENV
          else
            echo "BUCKET=optic-demo-website-staging" >> $GITHUB_ENV
            echo "CLOUDFRONT_DIST=E937BFTMG9NX3" >> $GITHUB_ENV
          fi
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@9d04a51fc17daddb0eb127933aaa950af1e3ff97 # they dont give us any tags :\
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Node
        uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d # v1.4.4
        with:
          node-version: 12
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@1417e62aeacec5e7fbe447bb7712d50847507342 # v1.5.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@060516122e7b4cc1cc3d4614a998adbb93d3fbf2 # v1.2.2
      - run: |
          echo "DOCKER_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "TAG=${BRANCH}-b${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "USER=${GITHUB_ACTOR}" >> $GITHUB_ENV
      - run: task ui:ci
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILD_BOT_SLACK_WEBHOOK_URL }}
